"use client";

import {useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Member={user_id:string;full_name?:string|null};

export function CapacitySettings({organizationId,members}:{organizationId:string;members:Member[]}){
  const [userId,setUserId]=useState("");const [mon,setMon]=useState(8);const [tue,setTue]=useState(8);const [wed,setWed]=useState(8);const [thu,setThu]=useState(8);const [fri,setFri]=useState(8);const [sat,setSat]=useState(0);const [sun,setSun]=useState(0);const [maxDaily,setMaxDaily]=useState(10);const [maxWeekly,setMaxWeekly]=useState(44);const [absenceStart,setAbsenceStart]=useState("");const [absenceEnd,setAbsenceEnd]=useState("");const [reason,setReason]=useState("");const [msg,setMsg]=useState("");const s=createClient();
  const selected=members.find(m=>m.user_id===userId);
  async function saveProfile(){if(!userId)return;setMsg("");const {error}=await s.from("resource_capacity_profiles").upsert({organization_id:organizationId,owner_key:userId,display_name:selected?.full_name||"Pessoa",weekday_hours:{mon,tue,wed,thu,fri,sat,sun},max_daily_hours:maxDaily,max_weekly_hours:maxWeekly,active:true},{onConflict:"organization_id,owner_key"});setMsg(error?error.message:"Capacidade salva.")}
  async function addAbsence(){if(!userId||!absenceStart||!absenceEnd)return;setMsg("");const {error}=await s.from("resource_absences").insert({organization_id:organizationId,owner_key:userId,start_date:absenceStart,end_date:absenceEnd,hours_per_day:null,reason:reason||"Ausência"});setMsg(error?error.message:"Ausência registrada.")}
  return <section className="card"><h3 style={{marginTop:0}}>Calendário de capacidade</h3><p className="muted">Capacidade disponível é separada do limite legal. O padrão é 8 h de segunda a sexta, com teto de planejamento de 10 h/dia e 44 h/semana.</p><label className="label">Pessoa</label><select className="input" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Selecione...</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.user_id}</option>)}</select>
  <div className="grid grid-2" style={{marginTop:10}}>{[["Seg",mon,setMon],["Ter",tue,setTue],["Qua",wed,setWed],["Qui",thu,setThu],["Sex",fri,setFri],["Sáb",sat,setSat],["Dom",sun,setSun]].map(([l,v,setter]:any)=><label key={l} className="label">{l}<input className="input" type="number" min="0" max="10" step="0.5" value={v} onChange={e=>setter(Number(e.target.value))}/></label>)}</div>
  <div className="grid grid-2"><label className="label">Máx. diário<input className="input" type="number" min="1" max="10" value={maxDaily} onChange={e=>setMaxDaily(Number(e.target.value))}/></label><label className="label">Máx. semanal<input className="input" type="number" min="1" max="60" value={maxWeekly} onChange={e=>setMaxWeekly(Number(e.target.value))}/></label></div><button className="btn btn-primary btn-block" onClick={()=>void saveProfile()} disabled={!userId}>Salvar capacidade</button>
  <hr style={{border:0,borderTop:"1px solid var(--line)",margin:"18px 0"}}/><h3>Ausência / férias</h3><div className="grid grid-2"><label className="label">Início<input className="input" type="date" value={absenceStart} onChange={e=>setAbsenceStart(e.target.value)}/></label><label className="label">Fim<input className="input" type="date" value={absenceEnd} onChange={e=>setAbsenceEnd(e.target.value)}/></label></div><label className="label">Motivo<input className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Férias, licença, indisponibilidade..."/></label><button className="btn btn-outline btn-block" onClick={()=>void addAbsence()} disabled={!userId||!absenceStart||!absenceEnd}>Registrar ausência</button>{msg&&<div className="notice" style={{marginTop:10}}>{msg}</div>}</section>
}
