"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";

export function CapacityManager({organizationId,members,projects}:{organizationId:string;members:any[];projects:any[]}) {
  const [user,setUser]=useState(""),[project,setProject]=useState(""),[allocation,setAllocation]=useState("100"),[hours,setHours]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[role,setRole]=useState(""),[msg,setMsg]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();const s=createClient();const{error}=await s.from("resource_allocations").insert({organization_id:organizationId,user_id:user,project_id:project,allocation_percent:Number(allocation),capacity_hours_per_week:hours?Number(hours):null,start_date:start||null,end_date:end||null,role_label:role||null});if(error)setMsg(error.message);else location.reload()}
  return <form className="card form" onSubmit={submit}><h2>Nova alocação</h2><div className="field"><label>Pessoa</label><select className="select" value={user} onChange={e=>setUser(e.target.value)} required><option value="">Selecionar</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.email||"Usuário"}</option>)}</select></div><div className="field"><label>Projeto</label><select className="select" value={project} onChange={e=>setProject(e.target.value)} required><option value="">Selecionar</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="grid grid-2"><div className="field"><label>Alocação %</label><input className="input" type="number" min="1" max="100" value={allocation} onChange={e=>setAllocation(e.target.value)}/></div><div className="field"><label>Horas/semana</label><input className="input" type="number" min="0" value={hours} onChange={e=>setHours(e.target.value)}/></div></div><div className="grid grid-2"><div className="field"><label>Início</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>Fim</label><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div className="field"><label>Função</label><input className="input" value={role} onChange={e=>setRole(e.target.value)} placeholder="PM, especialista, sponsor..."/></div><button className="btn btn-primary btn-block">Adicionar alocação</button>{msg&&<div className="error">{msg}</div>}</form>
}
