"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";

export function ActivityCreator({organizationId,projectId,members}:{organizationId:string;projectId:string;members:any[]}) {
  const [title,setTitle]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[owner,setOwner]=useState(""),[priority,setPriority]=useState("medium"),[status,setStatus]=useState("todo"),[hours,setHours]=useState(""),[msg,setMsg]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();const s=createClient();const{error}=await s.from("activities").insert({organization_id:organizationId,project_id:projectId,title:title.trim(),start_date:start||null,due_date:end||null,primary_owner_id:owner||null,priority,status,estimated_hours:hours?Number(hours):null});if(error)setMsg(error.message);else location.reload()}
  return <form className="card form" onSubmit={submit}><h2>Nova atividade</h2><div className="field"><label>Título</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} required/></div><div className="grid grid-2"><div className="field"><label>Início</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>Fim</label><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div className="field"><label>Responsável</label><select className="select" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Sem responsável</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.email||"Usuário"}</option>)}</select></div><div className="grid grid-2"><div className="field"><label>Prioridade</label><select className="select" value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div><div className="field"><label>Status</label><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="backlog">Backlog</option><option value="todo">A fazer</option><option value="in_progress">Em andamento</option><option value="blocked">Bloqueada</option><option value="in_review">Revisão</option><option value="done">Concluída</option></select></div></div><div className="field"><label>Horas estimadas</label><input className="input" type="number" min="0" value={hours} onChange={e=>setHours(e.target.value)}/></div><button className="btn btn-primary btn-block">Adicionar atividade</button>{msg&&<div className="error">{msg}</div>}</form>
}

export function RiskCreator({organizationId,projectId}:{organizationId:string;projectId:string}) {
  const [title,setTitle]=useState(""),[category,setCategory]=useState(""),[probability,setProbability]=useState("medium"),[impact,setImpact]=useState("medium"),[mitigation,setMitigation]=useState(""),[review,setReview]=useState(""),[msg,setMsg]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();const s=createClient();const{error}=await s.from("risks").insert({organization_id:organizationId,project_id:projectId,title:title.trim(),category:category||null,probability,impact,mitigation:mitigation||null,review_date:review||null});if(error)setMsg(error.message);else location.reload()}
  return <form className="card form" onSubmit={submit}><h2>Novo risco</h2><div className="field"><label>Risco</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} required/></div><div className="field"><label>Categoria</label><input className="input" value={category} onChange={e=>setCategory(e.target.value)} placeholder="Prazo, financeiro, técnico..."/></div><div className="grid grid-2"><div className="field"><label>Probabilidade</label><select className="select" value={probability} onChange={e=>setProbability(e.target.value)}><option value="very_low">Muito baixa</option><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="very_high">Muito alta</option></select></div><div className="field"><label>Impacto</label><select className="select" value={impact} onChange={e=>setImpact(e.target.value)}><option value="very_low">Muito baixo</option><option value="low">Baixo</option><option value="medium">Médio</option><option value="high">Alto</option><option value="very_high">Muito alto</option></select></div></div><div className="field"><label>Mitigação</label><textarea className="textarea" value={mitigation} onChange={e=>setMitigation(e.target.value)}/></div><div className="field"><label>Próxima revisão</label><input className="input" type="date" value={review} onChange={e=>setReview(e.target.value)}/></div><button className="btn btn-primary btn-block">Adicionar risco ao projeto</button>{msg&&<div className="error">{msg}</div>}</form>
}

export function KpiCreator({organizationId,projectId}:{organizationId:string;projectId:string}) {
  const [name,setName]=useState(""),[unit,setUnit]=useState(""),[baseline,setBaseline]=useState(""),[target,setTarget]=useState(""),[current,setCurrent]=useState(""),[frequency,setFrequency]=useState("monthly"),[msg,setMsg]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();const s=createClient();const{error}=await s.from("kpis").insert({organization_id:organizationId,project_id:projectId,name:name.trim(),unit:unit||null,baseline:baseline?Number(baseline):null,target:target?Number(target):null,current_value:current?Number(current):null,frequency});if(error)setMsg(error.message);else location.reload()}
  return <form className="card form" onSubmit={submit}><h2>Novo KPI</h2><div className="field"><label>Indicador</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label>Unidade</label><input className="input" value={unit} onChange={e=>setUnit(e.target.value)} placeholder="%, R$, dias, unidades..."/></div><div className="grid grid-2"><div className="field"><label>Baseline</label><input className="input" type="number" step="any" value={baseline} onChange={e=>setBaseline(e.target.value)}/></div><div className="field"><label>Meta</label><input className="input" type="number" step="any" value={target} onChange={e=>setTarget(e.target.value)}/></div></div><div className="field"><label>Atual</label><input className="input" type="number" step="any" value={current} onChange={e=>setCurrent(e.target.value)}/></div><div className="field"><label>Periodicidade</label><select className="select" value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option></select></div><button className="btn btn-primary btn-block">Adicionar KPI ao projeto</button>{msg&&<div className="error">{msg}</div>}</form>
}

export function FinanceCreator({organizationId,projectId}:{organizationId:string;projectId:string}) {
  const [budget,setBudget]=useState(""),[actual,setActual]=useState(""),[committed,setCommitted]=useState(""),[forecast,setForecast]=useState(""),[saving,setSaving]=useState(""),[benefit,setBenefit]=useState(""),[msg,setMsg]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();const s=createClient();const{error}=await s.from("budgets").insert({organization_id:organizationId,project_id:projectId,budget:Number(budget||0),actual:Number(actual||0),committed:Number(committed||0),forecast:Number(forecast||0),saving:Number(saving||0),benefit:Number(benefit||0)});if(error)setMsg(error.message);else location.reload()}
  return <form className="card form" onSubmit={submit}><h2>Registrar financeiro</h2><div className="grid grid-2">{[["Orçamento",budget,setBudget],["Realizado",actual,setActual],["Comprometido",committed,setCommitted],["Forecast",forecast,setForecast],["Saving",saving,setSaving],["Benefício",benefit,setBenefit]].map(([l,v,set]:any)=><div className="field" key={l}><label>{l}</label><input className="input" type="number" step="any" value={v} onChange={e=>set(e.target.value)}/></div>)}</div><button className="btn btn-primary btn-block">Salvar financeiro no projeto</button>{msg&&<div className="error">{msg}</div>}</form>
}


export function StatusReportCreator({organizationId,projectId,userId}:{organizationId:string;projectId:string;userId:string}) {
  const [start,setStart]=useState(""),[end,setEnd]=useState(""),[status,setStatus]=useState("on_track"),[progress,setProgress]=useState(""),[done,setDone]=useState(""),[next,setNext]=useState(""),[issues,setIssues]=useState(""),[decisions,setDecisions]=useState(""),[msg,setMsg]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();const s=createClient();const{error}=await s.from("status_reports").insert({organization_id:organizationId,project_id:projectId,period_start:start,period_end:end,overall_status:status,progress:progress?Number(progress):null,accomplishments:done||null,next_steps:next||null,issues:issues||null,decisions_needed:decisions||null,submitted_by:userId||null,submitted_at:new Date().toISOString()});if(error)setMsg(error.message);else location.reload()}
  return <form className="card form" onSubmit={submit}><h2>Novo Status Report</h2><div className="grid grid-2"><div className="field"><label>Período início</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)} required/></div><div className="field"><label>Período fim</label><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></div></div><div className="grid grid-2"><div className="field"><label>Status</label><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="on_track">No rumo</option><option value="attention">Atenção</option><option value="off_track">Fora do rumo</option></select></div><div className="field"><label>Progresso %</label><input className="input" type="number" min="0" max="100" value={progress} onChange={e=>setProgress(e.target.value)}/></div></div><div className="field"><label>Principais entregas</label><textarea className="textarea" value={done} onChange={e=>setDone(e.target.value)}/></div><div className="field"><label>Próximos passos</label><textarea className="textarea" value={next} onChange={e=>setNext(e.target.value)}/></div><div className="field"><label>Problemas</label><textarea className="textarea" value={issues} onChange={e=>setIssues(e.target.value)}/></div><div className="field"><label>Decisões necessárias</label><textarea className="textarea" value={decisions} onChange={e=>setDecisions(e.target.value)}/></div><button className="btn btn-primary btn-block">Publicar Status Report</button>{msg&&<div className="error">{msg}</div>}</form>
}
